title: ...
logo: 
description: Página do Projeto de Síntese Científica "Serviços ecossistêmicos como serviços de saúde - trajetórias competitivas para o uso da terra no bioma Amazônia e sua ligação com doenças transmitidas por vetores" 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
