title: Trajetorias
logo: 
description: Page of the Scientific synthesis project "Trajetorias: economic-social-environmental trajectories in the Amazon region" 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
